<?xml version="1.0"?>
<robot name="emiliobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <material name="blue">
        <color rgba="0 0 0.5 1" />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <material name="red">
        <color rgba="0.5 0 0 1" />
    </material>
    
    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <link name="base_footprint" />

    <!--
      _____ _    _           _____ _____ _____  _____ 
     / ____| |  | |   /\    / ____/ ____|_   _|/ ____|
    | |    | |__| |  /  \  | (___| (___   | | | (___  
    | |    |  __  | / /\ \  \___ \\___ \  | |  \___ \ 
    | |____| |  | |/ ____ \ ____) |___) |_| |_ ____) |
     \_____|_|  |_/_/    \_\_____/_____/|_____|_____/ 

    -->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <!--
     _____  _____ _____ _    _ _______  __          ___    _ ______ ______ _      
    |  __ \|_   _/ ____| |  | |__   __| \ \        / / |  | |  ____|  ____| |     
    | |__) | | || |  __| |__| |  | |     \ \  /\  / /| |__| | |__  | |__  | |     
    |  _  /  | || | |_ |  __  |  | |      \ \/  \/ / |  __  |  __| |  __| | |     
    | | \ \ _| || |__| | |  | |  | |       \  /\  /  | |  | | |____| |____| |____ 
    |_|  \_\_____\_____|_|  |_|  |_|        \/  \/   |_|  |_|______|______|______| 

    -->

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!--
     _      ______ ______ _______  __          ___    _ ______ ______ _      
    | |    |  ____|  ____|__   __| \ \        / / |  | |  ____|  ____| |     
    | |    | |__  | |__     | |     \ \  /\  / /| |__| | |__  | |__  | |     
    | |    |  __| |  __|    | |      \ \/  \/ / |  __  |  __| |  __| | |     
    | |____| |____| |       | |       \  /\  /  | |  | | |____| |____| |____ 
    |______|______|_|       |_|        \/  \/   |_|  |_|______|______|______|

    -->

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!--

      _______ ____  _____   __          ___    _ ______ ______ _      
     |__   __/ __ \|  __ \  \ \        / / |  | |  ____|  ____| |     
        | | | |  | | |__) |  \ \  /\  / /| |__| | |__  | |__  | |     
        | | | |  | |  ___/    \ \/  \/ / |  __  |  __| |  __| | |     
        | | | |__| | |         \  /\  /  | |  | | |____| |____| |____ 
        |_|  \____/|_|          \/  \/   |_|  |_|______|______|______|

    -->

    <link name="top_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_top_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="top_wheel_link" />
        <origin xyz="0 0 ${base_height
        
        }" rpy="0 0 0" />
        <axis xyz="0 1 0" /> 
    </joint>

    <!--
      _____           _____ _______ ______ _____   __          ___    _ ______ ______ _      
     / ____|   /\    / ____|__   __|  ____|  __ \  \ \        / / |  | |  ____|  ____| |     
    | |       /  \  | (___    | |  | |__  | |__) |  \ \  /\  / /| |__| | |__  | |__  | |     
    | |      / /\ \  \___ \   | |  |  __| |  _  /    \ \/  \/ / |  __  |  __| |  __| | |     
    | |____ / ____ \ ____) |  | |  | |____| | \ \     \  /\  /  | |  | | |____| |____| |____ 
     \_____/_/    \_\_____/   |_|  |______|_|  \_\     \/  \/   |_|  |_|______|______|______|                                                                                      
                                                                                          
    -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 -0.05" rpy="0 0 0" />
    </joint>
    
</robot>